// This file is automatically generated, so please do not edit it.
// Generated by `flutter_rust_bridge`@ 2.3.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<LddMagickTool>>
abstract class LddMagickTool implements RustOpaqueInterface {
  ///转黑白图
  Future<Uint8List> coverToMonochrome(
      {required List<int> data, required String format});

  ///转灰度图
  Future<Uint8List> covertToGrayColorImage(
      {required List<int> data, required String format});

  ///初始化
  factory LddMagickTool() =>
      RustLib.instance.api.crateApiMagickLddMagickToolNew();
}
