[package]
name = "ldd_tools"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = "=2.3.0"
image = "0.25.2"
imageproc = "0.25.0"
magick_rust = {git="https://github.com/mdddj/magick-rust"}